### ISSUE TITLE
Feature-Request - Capture and view user password settings and login options

### ISSUE THREAD

**Issue by mallej** [tuxudo/users#3]
As mentioned here: [https://macadmins.slack.com/archives/C066NK3K5/p1628683048050200](https://macadmins.slack.com/archives/C066NK3K5/p1628683048050200)

I suggest that the user module also shows whether the macOS user has set a password and whether Automatic Login (https://support.apple.com/en-us/HT201476) is enabled.

**Comment by tuxudo** [comment]
This has been added in with v2.2 of the module
