### ISSUE TITLE
Make collection of password hints optional configuration

### ISSUE THREAD

**Issue by dcoobs** [tuxudo/users#4]
Our Security team noticed that the users module uploads password hints for user accounts and weren't thrilled (some of the hints that users had were, more or less, their passwords).

A suggestion was made to open an issue to request making the collection of password hints an optional configuration with the default being off.

Discussion on Mac Admins Slack:
https://macadmins.slack.com/archives/C066NK3K5/p1631895716110600

**Comment by tuxudo** [comment]
This is resolved with version 1.10 of the module. 

It is possible to enable the collection of user account hints on clients using the preference domain MunkiReport with boolean key `user_account_hints_enabled` set to `true`. Alternatively, you can run `sudo defaults write /Library/Preferences/MunkiReport.plist user_account_hints_enabled -bool true` on the client.
