### ISSUE TITLE
v1.10 appears to break group membership

### ISSUE THREAD

**Issue by dcoobs** [tuxudo/users#5]
I updated the Users module to 1.10 yesterday and we noticed that a number of fields (group membership, ssh access, screen sharing access) are no longer updating for clients that have the latest version installed. I've seen the issue on both Monterey and Big Sur.

It appears that the client script is failing with a `KeyError: 'staff'` error at https://github.com/munkireport/users/blob/master/scripts/users.py#L101 and thus it sets group_memership to null without processing the remaining attributes (administrator, ssh, etc.)

**Pre-1.10:**
<img width="375" alt="Screen Shot 2021-12-15 at 9 26 45 AM" src="https://user-images.githubusercontent.com/12276948/146280732-b4908073-8a28-4f17-afa6-a1258e48b249.png">

**Post-1.10:**
<img width="350" alt="Screen Shot 2021-12-15 at 9 28 21 AM" src="https://user-images.githubusercontent.com/12276948/146280744-b051aa52-2cad-4c8c-bff5-59c4a9af24e8.png">

**Comment by tuxudo** [comment]
This should be addressed with PR #7, soon to be released version v2.2
